// gRPC Allocation Service Implementation
// Provides remote RPC endpoints for allocation operations

use crate::consensus_allocator::ConsensusAllocator;
use crate::health::HealthChecker;
use anyhow::Result;
use std::sync::Arc;
use tonic::{Request, Response, Status};
use tracing::{debug, info, warn, error};
use std::time::SystemTime;

// Proto generated code (would be auto-generated by tonic-build)
pub mod allocation {
    include!(concat!(env!("OUT_DIR"), "/scheduler.allocation.rs"));
}

use allocation::{
    allocation_service_server::{AllocationService, AllocationServiceServer},
    AllocateRequest, AllocateResponse, DeallocateRequest, DeallocateResponse,
    StatsRequest, StatsResponse, HealthRequest, HealthResponse, NodeInfo,
    MigrateRequest, MigrateResponse,
};

use crate::consensus_allocator::AllocationCommand;

/// gRPC Allocation Service implementation
pub struct AllocationServiceImpl {
    allocator: Arc<ConsensusAllocator>,
    health_checker: Arc<HealthChecker>,
    cluster_nodes: Vec<String>,
}

impl AllocationServiceImpl {
    pub fn new(
        allocator: Arc<ConsensusAllocator>,
        health_checker: Arc<HealthChecker>,
        cluster_nodes: Vec<String>,
    ) -> Self {
        Self {
            allocator,
            health_checker,
            cluster_nodes,
        }
    }
}

#[tonic::async_trait]
impl AllocationService for AllocationServiceImpl {
    /// Allocate blocks through consensus
    async fn allocate_blocks(
        &self,
        request: Request<AllocateRequest>,
    ) -> Result<Response<AllocateResponse>, Status> {
        let req = request.into_inner();
        let start = SystemTime::now();

        debug!(
            request_id = req.request_id,
            num_blocks = req.num_blocks,
            "Allocating blocks via gRPC"
        );

        match self.allocator.allocate_blocks(req.num_blocks as usize).await {
            Ok(block_ids) => {
                let latency = start.elapsed().unwrap_or_default().as_millis() as u32;

                info!(
                    request_id = req.request_id,
                    num_blocks = block_ids.len(),
                    latency_ms = latency,
                    "Blocks allocated successfully"
                );

                self.health_checker.record_check("allocation_success", true);

                Ok(Response::new(AllocateResponse {
                    success: true,
                    block_ids: block_ids.into_iter().map(|id| id as u64).collect(),
                    error: String::new(),
                    latency_ms: latency,
                    node_id: self.allocator.node_id().to_string(),
                }))
            }
            Err(e) => {
                let error_msg = format!("Allocation failed: {}", e);
                warn!(
                    request_id = req.request_id,
                    error = error_msg,
                    "Allocation failed"
                );

                self.health_checker.record_check("allocation_error", false);

                Ok(Response::new(AllocateResponse {
                    success: false,
                    block_ids: vec![],
                    error: error_msg,
                    latency_ms: start.elapsed().unwrap_or_default().as_millis() as u32,
                    node_id: self.allocator.node_id().to_string(),
                }))
            }
        }
    }

    /// Deallocate blocks through consensus
    async fn deallocate_blocks(
        &self,
        request: Request<DeallocateRequest>,
    ) -> Result<Response<DeallocateResponse>, Status> {
        let req = request.into_inner();
        let start = SystemTime::now();

        debug!(
            request_id = req.request_id,
            num_blocks = req.block_ids.len(),
            "Deallocating blocks via gRPC"
        );

        let block_ids: Vec<usize> = req.block_ids.into_iter().map(|id| id as usize).collect();

        match self.allocator.deallocate_blocks(&block_ids).await {
            Ok(_) => {
                let latency = start.elapsed().unwrap_or_default().as_millis() as u32;

                info!(
                    request_id = req.request_id,
                    count = block_ids.len(),
                    latency_ms = latency,
                    "Blocks deallocated successfully"
                );

                self.health_checker.record_check("deallocation_success", true);

                Ok(Response::new(DeallocateResponse {
                    success: true,
                    count: block_ids.len() as u32,
                    error: String::new(),
                    latency_ms: latency,
                }))
            }
            Err(e) => {
                let error_msg = format!("Deallocation failed: {}", e);
                warn!(
                    request_id = req.request_id,
                    error = error_msg,
                    "Deallocation failed"
                );

                self.health_checker.record_check("deallocation_error", false);

                Ok(Response::new(DeallocateResponse {
                    success: false,
                    count: 0,
                    error: error_msg,
                    latency_ms: start.elapsed().unwrap_or_default().as_millis() as u32,
                }))
            }
        }
    }

    /// Get cache statistics
    async fn get_stats(
        &self,
        _request: Request<StatsRequest>,
    ) -> Result<Response<StatsResponse>, Status> {
        match self.allocator.stats() {
            Ok(stats) => {
                let total = stats.total_blocks;
                let allocated = stats.allocated_blocks;
                let utilization = if total > 0 {
                    ((allocated as f64 / total as f64) * 100.0) as u32
                } else {
                    0
                };

                // Calculate average allocation latency from recorded metrics
                let avg_latency = {
                    let latencies = self.allocator.metrics.allocation_latency_ms.lock();
                    if latencies.is_empty() {
                        0
                    } else {
                        let sum: u64 = latencies.iter().sum();
                        (sum / latencies.len() as u64) as u32
                    }
                };

                Ok(Response::new(StatsResponse {
                    total_blocks: total as u64,
                    allocated_blocks: allocated as u64,
                    free_blocks: (total - allocated) as u64,
                    utilization_percent: utilization,
                    total_allocations: self
                        .allocator
                        .metrics
                        .total_allocations
                        .load(std::sync::atomic::Ordering::SeqCst),
                    total_deallocations: self
                        .allocator
                        .metrics
                        .total_deallocations
                        .load(std::sync::atomic::Ordering::SeqCst),
                    avg_latency_ms: avg_latency,
                    node_id: self.allocator.node_id().to_string(),
                }))
            }
            Err(e) => {
                error!("Failed to get stats: {}", e);
                Err(Status::internal("Failed to get stats"))
            }
        }
    }

    /// Get cluster health status
    async fn get_cluster_health(
        &self,
        _request: Request<HealthRequest>,
    ) -> Result<Response<HealthResponse>, Status> {
        let health = self.health_checker.get_health();
        let readiness = self.health_checker.get_readiness();
        let stats = self.allocator.stats().unwrap_or_default();
        let total = stats.total_blocks;
        let allocated = stats.allocated_blocks;
        let utilization = if total > 0 {
            ((allocated as f64 / total as f64) * 100.0) as u32
        } else {
            0
        };

        // Build node list from cluster_nodes
        let mut nodes: Vec<NodeInfo> = self
            .cluster_nodes
            .iter()
            .map(|node_id| {
                let is_self = node_id == self.allocator.node_id();
                NodeInfo {
                    node_id: node_id.clone(),
                    healthy: if is_self {
                        health.status == crate::health::HealthStatus::Healthy
                    } else {
                        // For remote nodes, mark healthy if they're in the cluster
                        // Real health would come from a failure detector
                        true
                    },
                    is_leader: if is_self {
                        self.allocator.is_leader()
                    } else {
                        false
                    },
                    utilization_percent: if is_self {
                        utilization
                    } else {
                        0 // Unknown for remote nodes until health check is performed
                    },
                    last_heartbeat: SystemTime::now()
                        .duration_since(SystemTime::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_secs(),
                }
            })
            .collect();

        // Ensure current node is in the list
        if !nodes.iter().any(|n| n.node_id == self.allocator.node_id()) {
            nodes.push(NodeInfo {
                node_id: self.allocator.node_id().to_string(),
                healthy: health.status == crate::health::HealthStatus::Healthy,
                is_leader: self.allocator.is_leader(),
                utilization_percent: utilization,
                last_heartbeat: SystemTime::now()
                    .duration_since(SystemTime::UNIX_EPOCH)
                    .unwrap_or_default()
                    .as_secs(),
            });
        }

        let total_nodes = nodes.len();
        let healthy_nodes = nodes.iter().filter(|n| n.healthy).count();
        let leader_id = if self.allocator.is_leader() {
            self.allocator.node_id().to_string()
        } else {
            String::new()
        };

        let quorum_status = match self.allocator.get_consensus_state() {
            crate::consensus::ConsensusState::Leader => "leader".to_string(),
            crate::consensus::ConsensusState::Follower => "follower".to_string(),
            crate::consensus::ConsensusState::Candidate => "candidate".to_string(),
        };

        Ok(Response::new(HealthResponse {
            healthy: health.status == crate::health::HealthStatus::Healthy,
            total_nodes: total_nodes as u32,
            healthy_nodes: healthy_nodes as u32,
            leader_id,
            nodes,
            quorum_status,
        }))
    }

    /// Migrate block to another node
    async fn migrate_block(
        &self,
        request: Request<MigrateRequest>,
    ) -> Result<Response<MigrateResponse>, Status> {
        let req = request.into_inner();
        let start = SystemTime::now();

        debug!(
            block_id = req.block_id,
            from_node = req.from_node,
            to_node = req.to_node,
            "Migrating block via gRPC"
        );

        // Validate that we are the source node
        if req.from_node != self.allocator.node_id() {
            return Ok(Response::new(MigrateResponse {
                success: false,
                block_id: req.block_id,
                from_node: req.from_node,
                to_node: req.to_node,
                error: format!(
                    "Source node mismatch: expected '{}', got '{}'",
                    self.allocator.node_id(),
                    req.from_node
                ),
            }));
        }

        // Validate that we are the leader (only leader can update ownership)
        if !self.allocator.is_leader() {
            return Ok(Response::new(MigrateResponse {
                success: false,
                block_id: req.block_id,
                from_node: req.from_node,
                to_node: req.to_node,
                error: "Only the leader node can migrate blocks".to_string(),
            }));
        }

        // Create migration command
        let command = AllocationCommand::MigrateBlock {
            block_id: req.block_id as usize,
            from_node: req.from_node.clone(),
            to_node: req.to_node.clone(),
        };

        // Apply through consensus to update ownership
        match self.allocator.apply_command(command).await {
            Ok(_) => {
                let latency = start.elapsed().unwrap_or_default().as_millis() as u32;

                info!(
                    block_id = req.block_id,
                    from_node = req.from_node,
                    to_node = req.to_node,
                    latency_ms = latency,
                    "Block migrated successfully"
                );

                self.health_checker.record_check("migration_success", true);

                Ok(Response::new(MigrateResponse {
                    success: true,
                    block_id: req.block_id,
                    from_node: req.from_node,
                    to_node: req.to_node,
                    error: String::new(),
                }))
            }
            Err(e) => {
                let error_msg = format!("Migration failed: {}", e);
                warn!(
                    block_id = req.block_id,
                    from_node = req.from_node,
                    to_node = req.to_node,
                    error = error_msg,
                    "Block migration failed"
                );

                self.health_checker.record_check("migration_error", false);

                Ok(Response::new(MigrateResponse {
                    success: false,
                    block_id: req.block_id,
                    from_node: req.from_node,
                    to_node: req.to_node,
                    error: error_msg,
                }))
            }
        }
    }
}

/// Create and configure gRPC server
pub async fn create_grpc_server(
    allocator: Arc<ConsensusAllocator>,
    health_checker: Arc<HealthChecker>,
    cluster_nodes: Vec<String>,
    port: u16,
) -> Result<()> {
    let addr = format!("[::]:{}", port).parse()?;
    let service = AllocationServiceImpl::new(allocator, health_checker, cluster_nodes);

    info!("Starting gRPC Allocation Service on {}", addr);

    tonic::transport::Server::builder()
        .add_service(AllocationServiceServer::new(service))
        .serve(addr)
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_allocation_service_creation() {
        // This would require setting up test fixtures
        // For now, ensure the module compiles and public API is accessible
    }
}
