// gRPC Allocation Service Implementation
// Provides remote RPC endpoints for allocation operations

use crate::consensus_allocator::ConsensusAllocator;
use crate::health::HealthChecker;
use anyhow::Result;
use std::sync::Arc;
use tokio::sync::RwLock;
use tonic::{Request, Response, Status};
use tracing::{debug, info, warn, error};
use std::time::SystemTime;

// Proto generated code (would be auto-generated by tonic-build)
// For now, we define the service interface
pub mod allocation {
    include!(concat!(env!("OUT_DIR"), "/scheduler.allocation.rs"));
}

use allocation::{
    allocation_service_server::{AllocationService, AllocationServiceServer},
    AllocateRequest, AllocateResponse, DeallocateRequest, DeallocateResponse,
    StatsRequest, StatsResponse, HealthRequest, HealthResponse, NodeInfo,
    MigrateRequest, MigrateResponse,
};

/// gRPC Allocation Service implementation
pub struct AllocationServiceImpl {
    allocator: Arc<ConsensusAllocator>,
    health_checker: Arc<HealthChecker>,
}

impl AllocationServiceImpl {
    pub fn new(
        allocator: Arc<ConsensusAllocator>,
        health_checker: Arc<HealthChecker>,
    ) -> Self {
        Self {
            allocator,
            health_checker,
        }
    }
}

#[tonic::async_trait]
impl AllocationService for AllocationServiceImpl {
    /// Allocate blocks through consensus
    async fn allocate_blocks(
        &self,
        request: Request<AllocateRequest>,
    ) -> Result<Response<AllocateResponse>, Status> {
        let req = request.into_inner();
        let start = SystemTime::now();

        debug!(
            request_id = req.request_id,
            num_blocks = req.num_blocks,
            "Allocating blocks via gRPC"
        );

        // Perform allocation
        match self.allocator.allocate_blocks(req.num_blocks as usize).await {
            Ok(block_ids) => {
                let latency = start.elapsed().unwrap_or_default().as_millis() as u32;
                
                info!(
                    request_id = req.request_id,
                    num_blocks = block_ids.len(),
                    latency_ms = latency,
                    "Blocks allocated successfully"
                );

                self.health_checker.record_check("allocation_success", true);

                Ok(Response::new(AllocateResponse {
                    success: true,
                    block_ids: block_ids.into_iter().map(|id| id as u64).collect(),
                    error: String::new(),
                    latency_ms: latency,
                    node_id: self.allocator.node_id().to_string(),
                }))
            }
            Err(e) => {
                let error_msg = format!("Allocation failed: {}", e);
                warn!(
                    request_id = req.request_id,
                    error = error_msg,
                    "Allocation failed"
                );

                self.health_checker.record_check("allocation_error", false);

                Ok(Response::new(AllocateResponse {
                    success: false,
                    block_ids: vec![],
                    error: error_msg,
                    latency_ms: start.elapsed().unwrap_or_default().as_millis() as u32,
                    node_id: self.allocator.node_id().to_string(),
                }))
            }
        }
    }

    /// Deallocate blocks through consensus
    async fn deallocate_blocks(
        &self,
        request: Request<DeallocateRequest>,
    ) -> Result<Response<DeallocateResponse>, Status> {
        let req = request.into_inner();
        let start = SystemTime::now();

        debug!(
            request_id = req.request_id,
            num_blocks = req.block_ids.len(),
            "Deallocating blocks via gRPC"
        );

        // Convert block IDs
        let block_ids: Vec<usize> = req.block_ids.into_iter().map(|id| id as usize).collect();

        // Perform deallocation
        match self.allocator.deallocate_blocks(&block_ids).await {
            Ok(_) => {
                let latency = start.elapsed().unwrap_or_default().as_millis() as u32;

                info!(
                    request_id = req.request_id,
                    count = block_ids.len(),
                    latency_ms = latency,
                    "Blocks deallocated successfully"
                );

                self.health_checker.record_check("deallocation_success", true);

                Ok(Response::new(DeallocateResponse {
                    success: true,
                    count: block_ids.len() as u32,
                    error: String::new(),
                    latency_ms: latency,
                }))
            }
            Err(e) => {
                let error_msg = format!("Deallocation failed: {}", e);
                warn!(
                    request_id = req.request_id,
                    error = error_msg,
                    "Deallocation failed"
                );

                self.health_checker.record_check("deallocation_error", false);

                Ok(Response::new(DeallocateResponse {
                    success: false,
                    count: 0,
                    error: error_msg,
                    latency_ms: start.elapsed().unwrap_or_default().as_millis() as u32,
                }))
            }
        }
    }

    /// Get cache statistics
    async fn get_stats(
        &self,
        _request: Request<StatsRequest>,
    ) -> Result<Response<StatsResponse>, Status> {
        match self.allocator.stats() {
            Ok(stats) => {
                let total = stats.total_blocks;
                let allocated = stats.allocated_blocks;
                let utilization = if total > 0 {
                    ((allocated as f64 / total as f64) * 100.0) as u32
                } else {
                    0
                };

                Ok(Response::new(StatsResponse {
                    total_blocks: total as u64,
                    allocated_blocks: allocated as u64,
                    free_blocks: (total - allocated) as u64,
                    utilization_percent: utilization,
                    total_allocations: self
                        .allocator
                        .metrics
                        .total_allocations
                        .load(std::sync::atomic::Ordering::SeqCst),
                    total_deallocations: self
                        .allocator
                        .metrics
                        .total_deallocations
                        .load(std::sync::atomic::Ordering::SeqCst),
                    avg_latency_ms: 0, // TODO: Calculate from metrics
                    node_id: self.allocator.node_id().to_string(),
                }))
            }
            Err(e) => {
                error!("Failed to get stats: {}", e);
                Err(Status::internal("Failed to get stats"))
            }
        }
    }

    /// Get cluster health status
    async fn get_cluster_health(
        &self,
        _request: Request<HealthRequest>,
    ) -> Result<Response<HealthResponse>, Status> {
        let health = self.health_checker.get_health();
        let readiness = self.health_checker.get_readiness();

        Ok(Response::new(HealthResponse {
            healthy: health.status == crate::health::HealthStatus::Healthy,
            total_nodes: 3, // TODO: Get from consensus engine
            healthy_nodes: if readiness.status == crate::health::ReadinessStatus::Ready { 1 } else { 0 },
            leader_id: if self.allocator.is_leader() {
                self.allocator.node_id().to_string()
            } else {
                String::new()
            },
            nodes: vec![
                NodeInfo {
                    node_id: self.allocator.node_id().to_string(),
                    healthy: health.status == crate::health::HealthStatus::Healthy,
                    is_leader: self.allocator.is_leader(),
                    utilization_percent: 0, // TODO: Calculate from stats
                    last_heartbeat: SystemTime::now()
                        .duration_since(SystemTime::UNIX_EPOCH)
                        .unwrap_or_default()
                        .as_secs(),
                },
            ],
            quorum_status: "unknown".to_string(), // TODO: Get from consensus
        }))
    }

    /// Migrate block to another node
    async fn migrate_block(
        &self,
        request: Request<MigrateRequest>,
    ) -> Result<Response<MigrateResponse>, Status> {
        let req = request.into_inner();

        debug!(
            block_id = req.block_id,
            from_node = req.from_node,
            to_node = req.to_node,
            "Migrating block via gRPC"
        );

        // TODO: Implement block migration logic
        // This would involve:
        // 1. Creating a migration command
        // 2. Applying it through consensus
        // 3. Coordinating with source and target nodes

        Ok(Response::new(MigrateResponse {
            success: false,
            block_id: req.block_id,
            from_node: req.from_node,
            to_node: req.to_node,
            error: "Not implemented".to_string(),
        }))
    }
}

/// Create and configure gRPC server
pub async fn create_grpc_server(
    allocator: Arc<ConsensusAllocator>,
    health_checker: Arc<HealthChecker>,
    port: u16,
) -> Result<()> {
    let addr = format!("[::]:{}:{}", "", port).parse()?;
    let service = AllocationServiceImpl::new(allocator, health_checker);

    info!("Starting gRPC Allocation Service on {}", addr);

    tonic::transport::Server::builder()
        .add_service(AllocationServiceServer::new(service))
        .serve(addr)
        .await?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_allocation_service_creation() {
        // This would require setting up test fixtures
        // For now, just ensure the module compiles
    }
}
